### ISSUE TITLE
Disabled after locking the screen

### ISSUE THREAD

**Issue by buzzcz** [danigm/spotify-ad-blocker#3]
Hi,
First of all, I love this extension, thank you for it.
Although I noticed that when I lock my screen, the icon of the extension gets grey and therefore stops working.

OS: Fedora Silverblue 31
Gnome Shell: 3.34.4

**Comment by danigm** [comment]
This is because the `unlock-dialog` session mode doesn't allow extensions: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/sessionMode.js#L57

So all extensions are disabled when the screen is locked and enabled when unlocked. Right now I don't know any good way to keep the extension working when the screen is locked.

Maybe we can try to implement something upstream in gnome-shell to be able to keep some extensions working in all sessions, or at least in the `ulock-dialog` session mode.

**Comment by buzzcz** [comment]
Aha, I see. Although my issue is really that when I unlock the screen again, I have to click the icon again so that it starts working. Maybe if the extension was on by default or something like that would help.
Thanks for your time.
